agent:
  maintenance:
    - interval: 10s
      repository:
        location: /Users/gilles/.plakar
      retention: 24h

  tasks:
    - name: system
      repository:
        location: /Users/gilles/.plakar
      
      backup:
        path: /private/etc
        interval: 5s
        retention: 60s
        #check: true

      check:
        - interval: 10s
          path: /
          latest: true

      sync:
        - interval: 10s
          direction: with
          peer: /tmp/foobar
